"""Deterministic investigation of a margin at completion decrease, without a language model.

Answers "Why is this project's margin at completion decreasing?" by: reading the governed metric, comparing the
forecast versions, decomposing deterministically, walking the related objects, retrieving evidence, stating limits,
and submitting proposals for human review. It abstains when the decrease is not established. The report is
labelled "sans LLM" and never presented as generated by a model.
"""

from __future__ import annotations

import uuid
from datetime import date
from decimal import Decimal
from typing import Any

import sqlalchemy as sa
from sqlalchemy.engine import Connection

from app.audit.log import append_event, canonical_json, content_hash
from app.controlling.erosion import compare
from app.controlling.metrics import _rows, compute_project_metrics, fmt, month_first
from app.controlling.psr import month_before

QUESTION = "Pourquoi la marge à terminaison de ce projet baisse-t-elle ?"
SCHEMA_VERSION = 1


def _evidence(conn: Connection, snapshot_id: uuid.UUID, project_id: int, cutoff: date, previous_forecast_id: str | None) -> dict[str, Any]:
    month = month_first(cutoff)
    hours = _rows(
        conn,
        "select e.role, count(*) as entries, count(distinct e.employee_code) as people, sum(t.hours) as hours"
        " from marts.fact_timesheet t join marts.dim_employee e on e.snapshot_id = t.snapshot_id and e.employee_id = t.employee_id"
        " where t.snapshot_id = :s and t.project_id = :p and t.entry_date between :m and :cut group by 1 order by 1",
        s=snapshot_id, p=project_id, m=month, cut=cutoff,
    )
    planned = {r["role"]: r["hours"] for r in _rows(
        conn, "select resource_or_role as role, sum(planned_hours) as hours from planning.plan_line where version_id = :v"
        " and cost_category = 'LABOUR' and period = :m group by 1", v=previous_forecast_id, m=month)} if previous_forecast_id else {}
    purchases = _rows(
        conn,
        "select c.purchase_line_id, c.cost_category, c.order_date, c.ordered_amount from marts.fact_purchase_commitment c"
        " where c.snapshot_id = :s and c.project_id = :p and c.order_date between :m and :cut order by c.order_date",
        s=snapshot_id, p=project_id, m=month, cut=cutoff,
    )
    return {
        "timesheets_in_cutoff_month": [
            {"role": r["role"], "entries": r["entries"], "people": r["people"], "actual_hours": fmt(r["hours"], "h"),
             "planned_hours_previous_forecast": fmt(planned[r["role"]], "h") if r["role"] in planned else None,
             "ref": f"marts.fact_timesheet?project_id={project_id}&month={month:%Y-%m}&role={r['role']}"}
            for r in hours
        ],
        "purchase_lines_ordered_in_cutoff_month": [
            {"purchase_line_id": r["purchase_line_id"], "cost_category": r["cost_category"], "order_date": str(r["order_date"]),
             "ordered_amount": fmt(r["ordered_amount"]), "ref": f"purchase.order.line:{r['purchase_line_id']}"}
            for r in purchases
        ],
    }


def investigate_margin_erosion(conn: Connection, snapshot_id: uuid.UUID, project_code: str, cutoff: date) -> dict[str, Any]:
    current = compute_project_metrics(conn, snapshot_id, project_code, cutoff)
    previous = compute_project_metrics(conn, snapshot_id, project_code, month_before(cutoff))
    change = compare(current, previous, conn)
    steps = [
        {"step": "read_governed_metric", "metric_id": "forecast_margin_amount", "current": change.current, "previous": change.previous},
        {"step": "compare_versions", "current": current.versions.forecast, "previous": current.versions.previous_forecast},
    ]
    report: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION, "question": QUESTION, "mode": "DETERMINISTIC_NO_LLM", "label": "sans LLM",
        "project_code": project_code, "cutoff": str(cutoff), "snapshot_id": str(snapshot_id), "steps": steps,
        "observations": [], "hypotheses": [], "unresolved": [], "evidence_refs": [], "limits": [], "proposed_actions": [],
        "root_cause_status": "UNRESOLVED", "abstention_reason": None,
    }
    if change.status != "EROSION":
        report["status"] = "ABSTAINED"
        report["abstention_reason"] = (
            change.reason if change.status == "UNKNOWN"
            else f"no material decrease: margin change {fmt(change.margin_change)} EUR is within thresholds"
        )
        return report

    steps.append({"step": "deterministic_decomposition", **change.as_dict()})
    project_id = current.project["project_id"]
    previous_id = current.versions.previous_forecast["version_id"] if current.versions.previous_forecast else None
    evidence = _evidence(conn, snapshot_id, project_id, cutoff, previous_id)
    steps.append({"step": "traverse_objects", "paths": [
        "project -> work package WP20 -> timesheets -> employees",
        "project -> purchase order lines -> vendor bills",
        "project -> milestones -> customer invoices -> payments",
    ], "graph": "relational traversal on marts; ontology projection not deployed"})
    steps.append({"step": "retrieve_evidence", **evidence})

    observations = [{"type": "OBSERVED_FACT", "numeric_claim_refs": ["forecast_margin_amount"],
                     "text": f"Margin at completion moved from {change.previous['forecast_margin_amount']} to "
                             f"{change.current['forecast_margin_amount']} EUR ({fmt(change.margin_change)} EUR)."}]
    if change.revenue_change:
        observations.append({"type": "OBSERVED_FACT", "numeric_claim_refs": ["forecast_revenue_at_completion"],
                             "text": f"Revenue at completion changed by {fmt(change.revenue_change)} EUR."})
    for category, delta in change.by_category.items():
        if delta:
            observations.append({"type": "OBSERVED_FACT", "numeric_claim_refs": [f"eac.{category}"],
                                 "text": f"{category} cost at completion increased by {fmt(delta)} EUR." if delta > 0
                                 else f"{category} cost at completion decreased by {fmt(-delta)} EUR."})
    for role, detail in change.labour_by_role.items():
        if detail["hours_change"] != "0":
            observations.append({"type": "OBSERVED_FACT", "numeric_claim_refs": [f"hours_at_completion.{role}"],
                                 "text": f"{role} hours at completion changed by {detail['hours_change']} h"
                                         + (f" at {detail['rate']} EUR/h, {detail['cost_change']} EUR." if detail["rate"] else ".")})
    for item in evidence["timesheets_in_cutoff_month"]:
        if item["planned_hours_previous_forecast"] and Decimal(item["actual_hours"]) > Decimal(item["planned_hours_previous_forecast"]):
            observations.append({"type": "OBSERVED_FACT", "numeric_claim_refs": ["actual_hours"],
                                 "text": f"{item['role']} logged {item['actual_hours']} h in the cutoff month against "
                                         f"{item['planned_hours_previous_forecast']} h planned by the previous forecast "
                                         f"({item['people']} {'person' if item['people'] == 1 else 'people'})."})
    report["observations"] = observations
    report["residual"] = fmt(change.residual)
    report["evidence_refs"] = [i["ref"] for i in evidence["timesheets_in_cutoff_month"]] + [
        i["ref"] for i in evidence["purchase_lines_ordered_in_cutoff_month"]]

    notes = _rows(conn, "select value_text, author, evidence_ref from planning.assumption where version_id = :v"
                  " and key = 'forecast_change_note'", v=current.versions.forecast["version_id"])
    if notes:
        report["hypotheses"] = [{"type": "SUPPORTED_HYPOTHESIS", "text": n["value_text"], "evidence_refs": [n["evidence_ref"]],
                                 "support": f"statement recorded by {n['author']} with the forecast; consistent with the observed "
                                            "hours and purchase changes, not independently verified"} for n in notes]
        report["root_cause_status"] = "SUPPORTED_HYPOTHESIS"
    else:
        report["unresolved"].append({"type": "UNRESOLVED", "text": "no recorded explanation for the forecast change; ask the project manager"})
    report["limits"] = [
        "No approved document corpus is indexed yet: the forecast note is the only qualitative evidence.",
        "Extra hours and a recorded note are consistent with rework; they do not prove the client's responsibility.",
        "The ontology graph is not deployed; objects were traversed through relational marts.",
        "Thresholds used to call an erosion are demonstration settings, not financial standards.",
    ]
    report["proposed_actions"] = [
        {"action": "review_change_order_opportunity", "requires_role": "finance_approver", "status": "PENDING_REVIEW",
         "text": "Assess whether the design package comments qualify for a change order before further rework is absorbed."},
        {"action": "review_engineering_staffing", "requires_role": "finance_approver", "status": "PENDING_REVIEW",
         "text": "Review the engineering hours plan to completion with the project manager and resource coordinator."},
    ]
    report["status"] = "COMPLETED"
    steps.append({"step": "explain_with_limits", "observations": len(observations), "hypotheses": len(report["hypotheses"])})
    steps.append({"step": "submit_for_review", "proposals": len(report["proposed_actions"])})
    return report


def save_investigation(conn: Connection, report: dict[str, Any], actor: str = "service:investigation") -> uuid.UUID:
    investigation_id = uuid.uuid4()
    conn.execute(
        sa.text(
            "insert into decision.investigation (investigation_id, subject_type, subject_id, question, mode, snapshot_id, status,"
            " report, report_hash) values (:i, 'project', :p, :q, :m, :s, :st, cast(:r as jsonb), :h)"
        ),
        {"i": investigation_id, "p": report["project_code"], "q": report["question"], "m": report["mode"], "s": report["snapshot_id"],
         "st": report["status"], "r": canonical_json(report), "h": content_hash(report)},
    )
    for action in report["proposed_actions"]:
        conn.execute(
            sa.text("insert into decision.recommendation (recommendation_id, investigation_id, action_key, version, status,"
                    " proposed_action, payload_hash) values (:r, :i, :k, 1, 'PENDING_REVIEW', cast(:a as jsonb), :h)"),
            {"r": uuid.uuid4(), "i": investigation_id, "k": action["action"], "a": canonical_json(action), "h": content_hash(action)},
        )
    append_event(conn, actor=actor, action="investigation.saved", object_type="investigation", object_id=str(investigation_id),
                 payload={"project_code": report["project_code"], "status": report["status"], "report_hash": content_hash(report)})
    return investigation_id
